# Support me by using the funding links below
# Developed and Maintained by Waren Gonzaga

open_collective: wifi-passview
custom: ['https://wrngnz.ga/bmc','https://wrngnz.ga/paypal']

# Your donation means a lot to me to continue the development of open source project like this.
