# Support this project and me by using the official funding links below.
# Developed and maintained by Waren Gonzaga.

open_collective: wifi-passview
custom: ['https://warengonzaga.com/donate']

# Your donation and support means a lot to me to continue the development my open source projects just like this.
